# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-17 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='handler_name',
            field=models.CharField(default='trigger', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
