# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-17 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170817_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plugin',
            old_name='handler_name',
            new_name='plugin_type',
        ),
    ]
