# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_devicegroup_friendly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='friendly_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
